In [36]:
import pandas as pd

In [37]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

### load the file as Data Frames

In [38]:
files = {
    'DimCity': 'DimCity.csv',
    'DimCustomer': 'DimCustomer.csv',
    'DimDate': 'DimDate.csv',
    'DimEmployee': 'DimEmployee.xlsx',
    'DimStockItem': 'DimStockItem.csv',
    'FactSale': 'FactSale.csv'
}

dimcity = pd.read_csv(files['DimCity'])
dimcustomer = pd.read_csv(files['DimCustomer'], thousands=',')
dimedate = pd.read_csv(files['DimDate'])
dimemployee = pd.read_excel(files['DimEmployee'])
dimstockitem = pd.read_csv(files['DimStockItem'])
factsale = pd.read_csv(files['FactSale'])

c:\Users\LOQ\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell H2 is marked as a date but the serial value 2958466 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\LOQ\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell H196 is marked as a date but the serial value 2958466 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\LOQ\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell H197 is marked as a date but the serial value 2958466 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\LOQ\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell H198 is marked as a date but the serial value 2958466 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\LOQ\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell H199 is marked as a date but the serial value 2958466 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\LOQ\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell H200 is marked as a date but the serial value 2958466 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\LOQ\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell H201 is marked as a date but the serial value 2958466 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\LOQ\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell H202 is marked as a date but the serial value 2958466 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\LOQ\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell H203 is marked as a date but the serial value 2958466 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\LOQ\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell H204 is marked as a date but the serial value 2958466 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\LOQ\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell H205 is marked as a date but the serial value 2958466 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\LOQ\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell H206 is marked as a date but the serial value 2958466 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\LOQ\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell H207 is marked as a date but the serial value 2958466 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\LOQ\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell H208 is marked as a date but the serial value 2958466 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\LOQ\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell H209 is marked as a date but the serial value 2958466 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\LOQ\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell H210 is marked as a date but the serial value 2958466 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\LOQ\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell H211 is marked as a date but the serial value 2958466 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\LOQ\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell H212 is marked as a date but the serial value 2958466 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\LOQ\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell H213 is marked as a date but the serial value 2958466 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)

### dimcity data

In [39]:
dimcity.columns, dimcity.shape

(Index(['City Key', 'City', 'State Province', 'Country', 'Sales Territory',
        'Location', 'Latest Recorded Population'],
       dtype='object'),
 (13028, 7))

In [40]:
dimcity.head(5)

,City Key,City,State Province,Country,Sales Territory,Location,Latest Recorded Population
0,18,Carson,California,United States,Far West,0xE6100000010C345A58816BEA4040AC1BEF8E0C925DC0,91714
1,19,Carson,Washington,United States,Far West,0xE6100000010C8B98C8BBD9DC4640CDFBA47F6E745EC0,2279
2,22,Carson City,Nevada,United States,Far West,0xE6100000010C8D919158F7944340B67526231DF15DC0,55274
3,27,Cartago,California,United States,Far West,0xE6100000010C168156050F294240936FB6B9B1815DC0,92
4,36,El Centro,California,United States,Far West,0xE6100000010C4C37894160654040E43DBD0809E45CC0,42598

### dimcustomer data

In [41]:
dimcustomer.columns, dimcustomer.shape

(Index(['Customer Data', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
        'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
        'Unnamed: 10', 'Unnamed: 11'],
       dtype='object'),
 (403, 12))

In [42]:
dimcustomer.head()

,Customer Data,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,Customer Key,WWI Customer ID,Customer,Bill To Customer,Category,Buying Group,Primary Contact,Postal Code,Credit Limit,Valid From,Valid To,Lineage Key
1,0,0,Unknown,NaN,NaN,NaN,NaN,NaN,? -,00:00.0,###############################################################################################################################################################################################################################################################,0
2,1,1,Tailspin Toys (Head Office),Tailspin Toys (Head Office),Novelty Shop,Tailspin Toys,Waldemar Fisar,90410,"? 100,000.000000",00:00.0,###############################################################################################################################################################################################################################################################,2
3,2,2,"Tailspin Toys (Sylvanite, MT)",Tailspin Toys (Head Office),Novelty Shop,Tailspin Toys,Lorena Cindric,90216,"? 100,000.000000",00:00.0,###############################################################################################################################################################################################################################################################,2
4,3,3,"Tailspin Toys (Peeples Valley, AZ)",Tailspin Toys (Head Office),Novelty Shop,Tailspin Toys,Bhaargav Rambhatla,90205,"? 100,000.000000",00:00.0,###############################################################################################################################################################################################################################################################,2

###### We have problem with the headers name & the first row

###### clean the headers

In [43]:
dimcustomer.columns = dimcustomer.iloc[0]
dimcustomer = dimcustomer[1:].reset_index(drop=True)

In [44]:
dimcustomer.columns

Index(['Customer Key', 'WWI Customer ID', 'Customer', 'Bill To Customer',
       'Category', 'Buying Group', 'Primary Contact', 'Postal Code',
       'Credit Limit', 'Valid From', 'Valid To', 'Lineage Key'],
      dtype='object', name=0)

In [45]:
dimcustomer.head(2)

,Customer Key,WWI Customer ID,Customer,Bill To Customer,Category,Buying Group,Primary Contact,Postal Code,Credit Limit,Valid From,Valid To,Lineage Key
0,0,0,Unknown,NaN,NaN,NaN,NaN,NaN,? -,00:00.0,###############################################################################################################################################################################################################################################################,0
1,1,1,Tailspin Toys (Head Office),Tailspin Toys (Head Office),Novelty Shop,Tailspin Toys,Waldemar Fisar,90410,"? 100,000.000000",00:00.0,###############################################################################################################################################################################################################################################################,2

###### clean Credit Limit column

In [46]:
len(dimcustomer.loc[:,'Credit Limit']) - len(dimcustomer.loc[:,'Credit Limit'].str.startswith('? '))

0

In [47]:
dimcustomer['Credit Limit'] = dimcustomer['Credit Limit'].str[2:]

In [48]:
len(dimcustomer.loc[:,'Credit Limit']) - len(dimcustomer.loc[:,'Credit Limit'].str.startswith('.000000'))

0

In [49]:
dimcustomer['Credit Limit'] = dimcustomer['Credit Limit'].str.replace('.000000', '')
dimcustomer['Credit Limit'] = dimcustomer['Credit Limit'].str.replace(',', '')
dimcustomer['Credit Limit'] = dimcustomer['Credit Limit'].str.replace('-', '0')

In [50]:
dimcustomer['Credit Limit'] = dimcustomer['Credit Limit'].astype(float)
dimcustomer['Credit Limit'].dtype

dtype('float64')

###### clean the date columns

In [51]:
dimcustomer.head()

,Customer Key,WWI Customer ID,Customer,Bill To Customer,Category,Buying Group,Primary Contact,Postal Code,Credit Limit,Valid From,Valid To,Lineage Key
0,0,0,Unknown,NaN,NaN,NaN,NaN,NaN,0.0,00:00.0,###############################################################################################################################################################################################################################################################,0
1,1,1,Tailspin Toys (Head Office),Tailspin Toys (Head Office),Novelty Shop,Tailspin Toys,Waldemar Fisar,90410,100000.0,00:00.0,###############################################################################################################################################################################################################################################################,2
2,2,2,"Tailspin Toys (Sylvanite, MT)",Tailspin Toys (Head Office),Novelty Shop,Tailspin Toys,Lorena Cindric,90216,100000.0,00:00.0,###############################################################################################################################################################################################################################################################,2
3,3,3,"Tailspin Toys (Peeples Valley, AZ)",Tailspin Toys (Head Office),Novelty Shop,Tailspin Toys,Bhaargav Rambhatla,90205,100000.0,00:00.0,###############################################################################################################################################################################################################################################################,2
4,4,4,"Tailspin Toys (Medicine Lodge, KS)",Tailspin Toys (Head Office),Novelty Shop,Tailspin Toys,Daniel Roman,90152,100000.0,00:00.0,###############################################################################################################################################################################################################################################################,2

In [52]:
dimcustomer[['Valid From']].head()

0 Valid From
0    00:00.0
1    00:00.0
2    00:00.0
3    00:00.0
4    00:00.0

In [53]:
dimcustomer['Valid From'] = pd.to_datetime(dimcustomer['Valid From'], errors='coerce')

In [91]:
dimcustomer[['Valid From']].head(10)

0 Valid From
0 2026-03-18
1 2026-03-18
2 2026-03-18
3 2026-03-18
4 2026-03-18
5 2026-03-18
6 2026-03-18
7 2026-03-18
8 2026-03-18
9 2026-03-18

In [55]:
dimcustomer['Valid To'] = pd.to_datetime(dimcustomer['Valid To'], errors = 'coerce')

In [56]:
len(dimcustomer['Valid To']) - dimcustomer['Valid To'].isna().sum()

np.int64(0)

In [57]:
dimcustomer['Valid To'].fillna(pd.Timestamp('2099-12-31'), inplace=True)

C:\Users\LOQ\AppData\Local\Temp\ipykernel_8664\1522609166.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dimcustomer['Valid To'].fillna(pd.Timestamp('2099-12-31'), inplace=True)

In [58]:
dimcustomer[['Valid To']].head(3)

0   Valid To
0 2099-12-31
1 2099-12-31
2 2099-12-31

#### A final look at the data

In [59]:
f"{dimcustomer.info()}  len: ({len(dimcustomer)})   shape: {dimcustomer.shape}"

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 402 entries, 0 to 401
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Customer Key      402 non-null    object
 1   WWI Customer ID   402 non-null    object
 2   Customer          402 non-null    object
 3   Bill To Customer  401 non-null    object
 4   Category          401 non-null    object
 5   Buying Group      401 non-null    object
 6   Primary Contact   401 non-null    object
 7   Postal Code       401 non-null    object
 8   Credit Limit      402 non-null    float64
 9   Valid From        402 non-null    datetime64[ns]
 10  Valid To          402 non-null    datetime64[ns]
 11  Lineage Key       402 non-null    object
dtypes: datetime64[ns](2), float64(1), object(9)
memory usage: 37.8+ KB

'None  len: (402)   shape: (402, 12)'

### DimEmployee data

In [60]:
dimemployee.columns, dimemployee.shape

(Index(['Employee Key', 'WWI Employee ID', 'Employee', 'Preferred Name',
        'Is Salesperson', 'Photo', 'Valid From', 'Valid To', 'Lineage Key'],
       dtype='object'),
 (212, 9))

In [61]:
dimemployee.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 212 entries, 0 to 211
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Employee Key     212 non-null    int64
 1   WWI Employee ID  212 non-null    int64
 2   Employee         212 non-null    object
 3   Preferred Name   211 non-null    object
 4   Is Salesperson   212 non-null    int64
 5   Photo            0 non-null      float64
 6   Valid From       212 non-null    datetime64[ns]
 7   Valid To         193 non-null    datetime64[ns]
 8   Lineage Key      212 non-null    int64
dtypes: datetime64[ns](2), float64(1), int64(4), object(2)
memory usage: 15.0+ KB

In [62]:
dimemployee.head()

,Employee Key,WWI Employee ID,Employee,Preferred Name,Is Salesperson,Photo,Valid From,Valid To,Lineage Key
0,0,0,Unknown,NaN,0,NaN,2013-01-01,NaT,0
1,1,14,Lily Code,Lily,1,NaN,2013-01-01,2013-01-01 08:00:00,3
2,2,4,Isabella Rupp,Isabella,0,NaN,2013-01-01,2013-01-01 08:00:00,3
3,3,11,Ethan Onslow,Ethan,0,NaN,2013-01-01,2013-01-04 08:00:00,3
4,4,7,Amy Trefl,Amy,1,NaN,2013-01-01,2013-01-05 08:00:00,3

##### start cleaning

In [63]:
dimemployee = dimemployee.drop(axis=0, index=0).reset_index(drop=True)

In [64]:
dimemployee.head()

,Employee Key,WWI Employee ID,Employee,Preferred Name,Is Salesperson,Photo,Valid From,Valid To,Lineage Key
0,1,14,Lily Code,Lily,1,NaN,2013-01-01,2013-01-01 08:00:00,3
1,2,4,Isabella Rupp,Isabella,0,NaN,2013-01-01,2013-01-01 08:00:00,3
2,3,11,Ethan Onslow,Ethan,0,NaN,2013-01-01,2013-01-04 08:00:00,3
3,4,7,Amy Trefl,Amy,1,NaN,2013-01-01,2013-01-05 08:00:00,3
4,5,19,Jai Shand,Jai,0,NaN,2013-01-01,2013-01-06 08:00:00,3

In [65]:
dimemployee['Is Salesperson'].replace({1:True, 0:False}, inplace=True)

C:\Users\LOQ\AppData\Local\Temp\ipykernel_8664\3279908285.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dimemployee['Is Salesperson'].replace({1:True, 0:False}, inplace=True)
C:\Users\LOQ\AppData\Local\Temp\ipykernel_8664\3279908285.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dimemployee['Is Salesperson'].replace({1:True, 0:False}, inplace=True)

In [66]:
dimemployee.head(4)

,Employee Key,WWI Employee ID,Employee,Preferred Name,Is Salesperson,Photo,Valid From,Valid To,Lineage Key
0,1,14,Lily Code,Lily,True,NaN,2013-01-01,2013-01-01 08:00:00,3
1,2,4,Isabella Rupp,Isabella,False,NaN,2013-01-01,2013-01-01 08:00:00,3
2,3,11,Ethan Onslow,Ethan,False,NaN,2013-01-01,2013-01-04 08:00:00,3
3,4,7,Amy Trefl,Amy,True,NaN,2013-01-01,2013-01-05 08:00:00,3

In [67]:
dimemployee['Employee'] = dimemployee['Employee'].str.strip()
dimemployee['Preferred Name'] = dimemployee['Preferred Name'].str.strip()

In [68]:
dimemployee['Photo'].notna().sum()

np.int64(0)

In [69]:
dimemployee.drop(columns=['Photo'], inplace=True)

In [70]:
dimemployee.head()

,Employee Key,WWI Employee ID,Employee,Preferred Name,Is Salesperson,Valid From,Valid To,Lineage Key
0,1,14,Lily Code,Lily,True,2013-01-01,2013-01-01 08:00:00,3
1,2,4,Isabella Rupp,Isabella,False,2013-01-01,2013-01-01 08:00:00,3
2,3,11,Ethan Onslow,Ethan,False,2013-01-01,2013-01-04 08:00:00,3
3,4,7,Amy Trefl,Amy,True,2013-01-01,2013-01-05 08:00:00,3
4,5,19,Jai Shand,Jai,False,2013-01-01,2013-01-06 08:00:00,3

### DimStockItem data

In [71]:
dimstockitem.columns, dimstockitem.shape

(Index([',,', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
        'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
        'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
        'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
        'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20'],
       dtype='object'),
 (673, 21))

In [72]:
dimstockitem.head()

,",,",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20
0,Stock Item Key,WWI Stock Item ID,Stock Item,Color,Selling Package,Buying Package,Brand,Size,Lead Time Days,Quantity Per Outer,Is Chiller Stock,Barcode,Tax Rate,Unit Price,Recommended Retail Price,Typical Weight Per Unit,Photo,Discount,Valid From,Valid To,Lineage Key
1,0,0,Unknown,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,0,0,? -,0,NaN,NaN,00:00.0,###############################################################################################################################################################################################################################################################,0
2,1,219,Void fill 400 L bag (White) 400L,NaN,Each,Each,NaN,400L,14,10,0,NaN,14,50,? 74.750,1,NaN,NaN,00:00.0,00:00.0,5
3,2,218,Void fill 300 L bag (White) 300L,NaN,Each,Each,NaN,300L,14,10,0,NaN,14,37.5,? 56.060,0.75,NaN,NaN,00:00.0,00:00.0,5
4,3,217,Void fill 200 L bag (White) 200L,NaN,Each,Each,NaN,200L,14,10,0,NaN,14,25,? 37.380,0.5,NaN,NaN,00:00.0,00:00.0,5

##### clean headers

In [73]:
dimstockitem.columns = dimstockitem.iloc[0]
dimstockitem = dimstockitem.reset_index(drop=True)

In [74]:
dimstockitem.head()

,Stock Item Key,WWI Stock Item ID,Stock Item,Color,Selling Package,Buying Package,Brand,Size,Lead Time Days,Quantity Per Outer,Is Chiller Stock,Barcode,Tax Rate,Unit Price,Recommended Retail Price,Typical Weight Per Unit,Photo,Discount,Valid From,Valid To,Lineage Key
0,Stock Item Key,WWI Stock Item ID,Stock Item,Color,Selling Package,Buying Package,Brand,Size,Lead Time Days,Quantity Per Outer,Is Chiller Stock,Barcode,Tax Rate,Unit Price,Recommended Retail Price,Typical Weight Per Unit,Photo,Discount,Valid From,Valid To,Lineage Key
1,0,0,Unknown,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,0,0,? -,0,NaN,NaN,00:00.0,###############################################################################################################################################################################################################################################################,0
2,1,219,Void fill 400 L bag (White) 400L,NaN,Each,Each,NaN,400L,14,10,0,NaN,14,50,? 74.750,1,NaN,NaN,00:00.0,00:00.0,5
3,2,218,Void fill 300 L bag (White) 300L,NaN,Each,Each,NaN,300L,14,10,0,NaN,14,37.5,? 56.060,0.75,NaN,NaN,00:00.0,00:00.0,5
4,3,217,Void fill 200 L bag (White) 200L,NaN,Each,Each,NaN,200L,14,10,0,NaN,14,25,? 37.380,0.5,NaN,NaN,00:00.0,00:00.0,5

In [75]:
dimstockitem.drop(axis=0, index=0, inplace=True)
dimstockitem = dimstockitem.reset_index(drop=True)

In [76]:
dimstockitem.head()

,Stock Item Key,WWI Stock Item ID,Stock Item,Color,Selling Package,Buying Package,Brand,Size,Lead Time Days,Quantity Per Outer,Is Chiller Stock,Barcode,Tax Rate,Unit Price,Recommended Retail Price,Typical Weight Per Unit,Photo,Discount,Valid From,Valid To,Lineage Key
0,0,0,Unknown,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,0,0,? -,0,NaN,NaN,00:00.0,###############################################################################################################################################################################################################################################################,0
1,1,219,Void fill 400 L bag (White) 400L,NaN,Each,Each,NaN,400L,14,10,0,NaN,14,50,? 74.750,1,NaN,NaN,00:00.0,00:00.0,5
2,2,218,Void fill 300 L bag (White) 300L,NaN,Each,Each,NaN,300L,14,10,0,NaN,14,37.5,? 56.060,0.75,NaN,NaN,00:00.0,00:00.0,5
3,3,217,Void fill 200 L bag (White) 200L,NaN,Each,Each,NaN,200L,14,10,0,NaN,14,25,? 37.380,0.5,NaN,NaN,00:00.0,00:00.0,5
4,4,216,Void fill 100 L bag (White) 100L,NaN,Each,Each,NaN,100L,14,10,0,NaN,14,12.5,? 18.690,0.25,NaN,NaN,00:00.0,00:00.0,5

##### clean Recommended Retail Price

In [77]:
dimstockitem.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 672 entries, 0 to 671
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Stock Item Key            672 non-null    object
 1   WWI Stock Item ID         672 non-null    object
 2   Stock Item                672 non-null    object
 3   Color                     360 non-null    object
 4   Selling Package           671 non-null    object
 5   Buying Package            671 non-null    object
 6   Brand                     67 non-null     object
 7   Size                      468 non-null    object
 8   Lead Time Days            672 non-null    object
 9   Quantity Per Outer        672 non-null    object
 10  Is Chiller Stock          672 non-null    object
 11  Barcode                   16 non-null     object
 12  Tax Rate                  672 non-null    object
 13  Unit Price                672 non-null    object
 14  Recommended Retail Price  672 non-null    object
 15  Typical Weight Per Unit   672 non-null    object
 16  Photo                     0 non-null      object
 17  Discount                  0 non-null      object
 18  Valid From                672 non-null    object
 19  Valid To                  672 non-null    object
 20  Lineage Key               672 non-null    object
dtypes: object(21)
memory usage: 110.4+ KB

In [78]:
dimstockitem.drop(columns=['Photo', 'Discount'], inplace=True)

In [79]:
dimstockitem['Recommended Retail Price'] = dimstockitem['Recommended Retail Price'].str.replace('? ', '')
dimstockitem['Recommended Retail Price'] = dimstockitem['Recommended Retail Price'].str.replace(',', '')

In [80]:
dimstockitem['Recommended Retail Price'].head(10)

0           -
1      74.750
2      56.060
3      37.380
4      18.690
5    2839.010
6     134.550
7     130.070
8       6.430
9       6.130
Name: Recommended Retail Price, dtype: object

In [81]:
dimstockitem['Recommended Retail Price'] = pd.to_numeric(
    dimstockitem['Recommended Retail Price'], 
    errors='coerce')

In [82]:
dimstockitem['Recommended Retail Price'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 672 entries, 0 to 671
Series name: Recommended Retail Price
Non-Null Count  Dtype
--------------  -----
671 non-null    float64
dtypes: float64(1)
memory usage: 5.4 KB

##### clean date columns

In [83]:
dimstockitem['Valid From'] = pd.to_datetime(dimstockitem['Valid From'], errors='coerce')
dimstockitem['Valid To'] = pd.to_datetime(dimstockitem['Valid To'], errors='coerce')

C:\Users\LOQ\AppData\Local\Temp\ipykernel_8664\662674449.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dimstockitem['Valid From'] = pd.to_datetime(dimstockitem['Valid From'], errors='coerce')
C:\Users\LOQ\AppData\Local\Temp\ipykernel_8664\662674449.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dimstockitem['Valid To'] = pd.to_datetime(dimstockitem['Valid To'], errors='coerce')

In [84]:
dimstockitem[['Valid From', 'Valid To']].head()

0 Valid From   Valid To
0 2026-03-18        NaT
1 2026-03-18 2026-03-18
2 2026-03-18 2026-03-18
3 2026-03-18 2026-03-18
4 2026-03-18 2026-03-18

### FactSale data

In [85]:
factsale.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26397 entries, 0 to 26396
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Sale Key              26397 non-null  int64
 1   City Key              26397 non-null  int64
 2   Customer Key          26397 non-null  int64
 3   Bill To Customer Key  26397 non-null  int64
 4   Stock Item Key        26397 non-null  int64
 5   Invoice Date Key      26397 non-null  object
 6   Delivery Date Key     26384 non-null  object
 7   Salesperson Key       26397 non-null  int64
 8   WWI Invoice ID        26397 non-null  int64
 9   Description           26397 non-null  object
 10  Package               26397 non-null  object
 11  Quantity              26397 non-null  int64
 12  Unit Price            26397 non-null  float64
 13  Tax Rate              26397 non-null  int64
 14  Total Excluding Tax   26397 non-null  float64
 15  Tax Amount            26397 non-null  float64
 16  Profit                26397 non-null  float64
 17  Total Including Tax   26397 non-null  float64
 18  Total Dry Items       26397 non-null  int64
 19  Total Chiller Items   26397 non-null  int64
 20  Lineage Key           26397 non-null  int64
dtypes: float64(5), int64(12), object(4)
memory usage: 4.2+ MB

In [86]:
factsale.head()

,Sale Key,City Key,Customer Key,Bill To Customer Key,Stock Item Key,Invoice Date Key,Delivery Date Key,Salesperson Key,WWI Invoice ID,Description,Package,Quantity,Unit Price,Tax Rate,Total Excluding Tax,Tax Amount,Profit,Total Including Tax,Total Dry Items,Total Chiller Items,Lineage Key
0,49265,41568,0,0,204,10/22/2013,10/23/2013,83,15189,DBA joke mug - mind if I join you? (White),Each,6,13.0,15,78.0,11.7,51.0,89.7,6,0,11
1,49372,48937,0,0,173,10/22/2013,10/23/2013,83,15218,Developer joke mug - a foo walks into a bar (Black),Each,6,13.0,15,78.0,11.7,51.0,89.7,6,0,11
2,50379,91464,0,0,174,10/28/2013,10/29/2013,70,15525,Developer joke mug - a foo walks into a bar (White),Each,6,13.0,15,78.0,11.7,51.0,89.7,6,0,11
3,51852,48937,0,0,171,11/6/2013,11/7/2013,74,15986,Developer joke mug - this code was generated by a tool (Black),Each,6,13.0,15,78.0,11.7,51.0,89.7,6,0,11
4,52374,89925,0,0,203,11/8/2013,11/9/2013,39,16138,DBA joke mug - mind if I join you? (Black),Each,6,13.0,15,78.0,11.7,51.0,89.7,6,0,11

In [87]:
cols = ['Invoice Date Key', 'Delivery Date Key']
factsale[cols] = factsale[cols].apply(
    lambda col: pd.to_datetime(col, errors='coerce'))

In [88]:
factsale[cols].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26397 entries, 0 to 26396
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Invoice Date Key   26397 non-null  datetime64[ns]
 1   Delivery Date Key  26384 non-null  datetime64[ns]
dtypes: datetime64[ns](2)
memory usage: 412.6 KB

### Save to csv

In [ ]:
data_frames = {
    'DimCity': dimcity,
    'DimCustomer': dimcustomer,
    'DimEmployee': dimemployee,
    'DimStockItem': dimstockitem,
    'FactSale': factsale
}


SAVE_FILES = False

if SAVE_FILES:
    import os
    output_path = r'C:/Users/LOQ/Desktop/Data Work/PowerBI Work Space/Projects/World wide importers/clean data'
    os.makedirs(output_path, exist_ok=True)

    # save cleaned dataframes to csv files
    for name, df in data_frames.items():
        df.to_csv(f'{output_path}/{name}_cleaned.csv', index=False)